#
# Default configuration, for configurations that are profile dependent
#

BaseWebProcessor:
  siteName: "Going offgrid"
  welcomeMessage: "Going offgrid"
  administratorEmail: "Pierre@LogicielCote.COM"
  siteVersion: "0.1.0"
