REC0144=[]
REC0150=[]
REC0156=[]
REC0158=[]
REC0159=[]
REC0160=[]
REC0162=[]
REC0163=[]
REC0164=[]
REC0165=[]
REC0166=[]
REC0167=[]
REC0170=[]
REC0171=[]
REC0172=[]
REC0173=[]
REC0174=[]
REC0175=[]
REC0177=[]
REC0178=[]
REC0179=[]
REC0181=[]
REC0182=[]
REC0184=[]
REC0185=[]
REC0186=[]
REC0188=["http://www.sitesandtrailsbc.ca/resources/REC0188/sitemaps/Miller%20Creek%20Rec%20Site.pdf"]
REC0190=[]
REC0191=["http://www.sitesandtrailsbc.ca/resources/REC0191/sitemaps/Roberts%20Lake%20Rec%20Site.pdf"]
REC0195=[]
REC0196=[]
REC0197=["http://www.sitesandtrailsbc.ca/resources/REC0197/sitemaps/Sayward%20Canoe%20Route%20Brochure%20and%20Map.pdf"]
REC0205=["http://www.sitesandtrailsbc.ca/resources/REC0205/sitemaps/Pine%20Point%20Rec%20Site.pdf"]
REC0206=["http://www.sitesandtrailsbc.ca/resources/REC0206/sitemaps/Maple_Grove%20Rec%20Site.pdf"]
REC0242=["http://www.sitesandtrailsbc.ca/resources/REC0242/sitemaps/Marble%20River%20Rec%20Site.pdf"]
REC0258=["http://www.sitesandtrailsbc.ca/resources/REC0258/sitemaps/Muchalat%20Lake%20Rec%20Site.pdf"]
REC0297=[]
REC0300=[]
REC0303=[]
REC0429=[]
REC1393=[]
REC1497=[]
REC1564=[]
REC16044=[]
REC16046=[]
REC16068=[]
REC16069=[]
REC16077=["http://www.sitesandtrailsbc.ca/resources/REC16077/sitemaps/Clint%20Beek%20Rec%20Site.pdf"]
REC16081=["http://www.sitesandtrailsbc.ca/resources/REC16081/sitemaps/Beaver%20Lake%20Rec%20Site%20ver4.pdf"]
REC16124=[]
REC16198=[]
REC169767=["http://www.sitesandtrailsbc.ca/resources/REC169767/sitemaps/Memekay%20Horse%20Camp%20Rec%20Site.pdf","http://www.sitesandtrailsbc.ca/resources/REC169767/sitemaps/Memekay%20Horse%20Camp%20direction%20map.pdf"]
REC1728=[]
REC1729=[]
REC1730=[]
REC1897=[]
REC191957=["http://www.sitesandtrailsbc.ca/resources/REC191957/sitemaps/Horse%20Camp%20Directional%20Map.pdf","http://www.sitesandtrailsbc.ca/resources/REC191957/sitemaps/Memekay%20Horse%20Camp%20Rec%20Site%20.pdf","http://www.sitesandtrailsbc.ca/resources/REC191957/sitemaps/Salmon%20Brewster%20Georeferenced%20Map.pdf","http://www.sitesandtrailsbc.ca/resources/REC191957/sitemaps/Salmon%20Brewster%20Horse%20Trail%20Brochure.pdf"]
REC204456=[]
REC204459=[]
REC2057=["http://www.sitesandtrailsbc.ca/resources/REC2057/sitemaps/Cedar%20Lake%20Rec%20Site%20(1.2%20MB).pdf"]
REC206138=[]
REC2069=["http://www.sitesandtrailsbc.ca/resources/REC2069/sitemaps/Help%20Lake%20Site%20Plan%20Map.pdf","http://www.sitesandtrailsbc.ca/resources/REC2069/sitemaps/Access%20Map%20to%20Help%20Lake.pdf"]
REC2081=["http://www.sitesandtrailsbc.ca/resources/REC2081/sitemaps/Blackwater%20Lake%20Access%20Directions.pdf","http://www.sitesandtrailsbc.ca/resources/REC2081/sitemaps/Blackwater%20Lake%20Site%20Plan.pdf"]
REC2362=[]
REC2371=[]
REC2466=["http://www.sitesandtrailsbc.ca/resources/REC2466/sitemaps/Sale%20Mtn%20Trail.pdf","http://www.sitesandtrailsbc.ca/resources/REC2466/sitemaps/Sale%20Mtn%20Trail_2019.pdf"]
REC2593=[]
REC2595=[]
REC2859=[]
REC3046=[]
REC3054=[]
REC3067=[]
REC3068=[]
REC3096=[]
REC3104=[]
REC3129=[]
REC3130=["http://www.sitesandtrailsbc.ca/resources/REC3130/sitemaps/FLORA%20LAKE.pdf"]
REC3131=[]
REC3198=[]
REC3199=[]
REC3201=[]
REC3202=["http://www.sitesandtrailsbc.ca/resources/REC3202/sitemaps/Beaver%20Lake%20Trail%20Map.pdf","http://www.sitesandtrailsbc.ca/resources/REC3202/sitemaps/Beaver%20Lake%20Site%20and%20Trail%20Map.pdf"]
REC3204=[]
REC32204=[]
REC32503=[]
REC32734=[]
REC3295=[]
REC33008=[]
REC3523=[]
REC4531=["http://www.sitesandtrailsbc.ca/resources/REC4531/sitemaps/Twin%20Lakes%20Trails.pdf"]
REC5671=[]
REC5750=[]
REC5810=[]
REC5884=["http://www.sitesandtrailsbc.ca/resources/REC5884/sitemaps/Scuitto%20Lake%20Campbell%20Lake%20Orientation%20Map.pdf"]
REC5988=[]
REC6047=[]
REC6079=["http://www.sitesandtrailsbc.ca/resources/REC6079/sitemaps/RIPPLE_RIDGE_TRAIL.pdf"]
REC6166=[]
REC6322=[]
REC6325=[]
REC6344=[]
REC6345=[]
REC6407=[]
REC6423=[]
REC6433=[]
REC6444=["http://www.sitesandtrailsbc.ca/resources/REC6444/sitemaps/Tlowils%20Lake%20Rec%20Site.pdf"]
REC6450=[]
REC6622=[]
REC6787=[]
REC6788=[]
REC6804=[]
REC98066=["http://www.sitesandtrailsbc.ca/resources/REC98066/sitemaps/Mt%20Beaven%20Trail.pdf"]
REC98321=["http://www.sitesandtrailsbc.ca/resources/REC98321/sitemaps/Eagle%20Pass%20Lookout%20Twin%20Lakes.pdf"]
